name: Deploy PG cluster

on:
  workflow_dispatch:
  
# env:
#   KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: homelab-runner-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Debug - Print KUBECONFIG
    #   run: | 
    #     echo "KUBECONFIG: ${KUBECONFIG}"

    # - name: Configure Kubectl
    #   run: |
    #     echo ${KUBECONFIG} | base64 --decode > kubeconfig.yaml

    - name: Create PG Cluster
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f pg-cluster/homelab-pg.yaml